# Generated by Django 5.2.3 on 2025-06-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_default_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
    ]
