# Generated by Django 5.2.3 on 2025-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_payroll_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
    ]
