# Generated by Django 5.2.3 on 2025-06-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_payroll_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
