# Generated by Django 5.2.3 on 2025-06-23 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_role_created_at_remove_role_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='lop_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
