# Generated by Django 5.2.3 on 2025-06-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_leavebalance_lop_count_alter_leave_requested_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
