# Generated by Django 5.2.3 on 2025-06-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_designation_alter_employeeprofile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='designation',
        ),
    ]
