# Generated by Django 5.2.3 on 2025-06-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_employeeprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.designation'),
        ),
    ]
