# Generated by Django 5.2.3 on 2025-06-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_employeeprofile_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timesheet',
        ),
    ]
