# Generated by Django 5.2.3 on 2025-06-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_timesheet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
