# Generated by Django 5.2.3 on 2025-06-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerating',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
